<a href="https://colab.research.google.com/github/CharlesRMcCullough/PyTorchYoutube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Tensors

In [2]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.7222,  1.0298,  1.4709,  0.4276],
        [-0.2668,  0.5310, -0.9057, -2.2412],
        [ 0.0262,  1.7314,  1.2448,  1.2685]])

In [3]:
tensor_3d = torch.ones(2, 3, 4)
tensor_3d

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [4]:
tensor_3d.dtype

torch.float32

In [5]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [6]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [7]:
tensor = torch.arange(10)
print(tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [8]:
tensor = tensor.reshape(2, 5)
print(tensor)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


#### Reshape if you don't know the number of itesm.

In [9]:
my_torch = torch.arange(10)
my_torch2 = my_torch.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

#### Reshape and view will update

In [13]:
my_torch4[1][3] = 5151
my_torch4

tensor([[   0,    1,    2,    3,    4],
        [4141, 4141, 4141, 5151, 4141]])

#### Slices

In [14]:
my_torch5 = torch.arange(10)
my_torch5[7]


tensor(7)

#### Grab slice

In [15]:
my_torch7 = my_torch5.reshape(5, 2)
my_torch7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [16]:
my_torch7[:, 1]

tensor([1, 3, 5, 7, 9])

#### Return column

In [18]:
my_torch7[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])